fixed some stuff
Picture2PC/Picture2Pc pull request #78
Opened 2024-10-16 18:28 UTC by GitbertFrank

2024-10-31 17:16 UTC, GrumpyDucc approved these changes
Gud changes

2024-11-01 17:03 UTC, mightytry requested changes
Should be repository and injected with Koin. The repository could also be moved to Common, but does not have to be.

2024-11-04 18:38 UTC, GitbertFrank commented
Who says it should be like that?

2024-11-04 18:51 UTC, GitbertFrank commented
Add proper documentation and instructions and ill do it

2024-12-24 14:16 UTC, GrumpyDucc approved these changes

2025-03-07 14:31 UTC, mightytry requested changes

2025-03-07 14:31 UTC, mightytry commented on android/src/main/kotlin/com/github/picture2pc/android/data/TrayNotificationHandler.kt
> +                .setContentIntent(PendingIntent.getActivity(
Title and content hard coded?

2025-03-07 14:31 UTC, mightytry commented on android/src/main/kotlin/com/github/picture2pc/android/ui/main/bigpicturescreen/elements/BottomOfScreen.kt
> +            },
why?

2025-03-07 14:31 UTC, mightytry commented on android/src/main/kotlin/com/github/picture2pc/android/viewmodel/camerascreenviewmodels/CameraViewModel.kt
> +            notificationHandler.displayNotification("Picture2PC", message, true)
Just a thought but I think it would be great if all text would be in one constant file like the descriptions.

2025-03-07 14:31 UTC, mightytry commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/ui/constants/Settings.kt
> +    const val NEW_PICTURE: String = "New picture received"
I meant something like this for all text.

2025-03-07 14:31 UTC, mightytry commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/viewmodel/mainscreen/PictureDisplayViewModel.kt
> +            if (unseenPictures.value + 1 > 0) message += " (${unseenPictures.value + 1} unseen pictures)"
Text here too.

2025-03-12 14:03 UTC, GrumpyDucc commented on android/src/main/kotlin/com/github/picture2pc/android/ui/main/bigpicturescreen/elements/BottomOfScreen.kt
> +            },
because auto refeactor, was problably in one line then ended up automatically doing this

2025-10-10 13:42 UTC, mightytry approved these changes

2025-10-10 14:00 UTC, merged