Fix/desktop/37 client does not have a name
Picture2PC/Picture2Pc pull request #86
Opened 2024-11-20 18:03 UTC by GrumpyDucc

2024-11-27 18:05 UTC, GrumpyDucc commented
@mightytry  mach auge

2025-01-08 01:18 UTC, mightytry requested changes
Sry but in Germany we say: "Wenn schon denn schon"

2025-01-08 01:18 UTC, mightytry commented on common/src/main/kotlin/com/github/picture2pc/common/data/preferences/PreferencesRepository.kt
> +    abstract fun loadPreferences(): Preferences
Would make these 2 methods `open` instead of `abstract`, because they don't need to be implemented

2025-01-08 01:18 UTC, mightytry commented on android/src/main/kotlin/com/github/picture2pc/android/data/serverpreferences/impl/AndroidPreferencesRepository.kt
> +    }
This would not be needed any more if `open`.

2025-01-08 01:18 UTC, mightytry commented on android/src/main/kotlin/com/github/picture2pc/android/ui/main/mainscreen/elements/ConnectableStateSwitch.kt
> +            onCheckedChange = { broadcastViewModel.setConnectable(it) },
Could be simplified like: `onCheckedChange= broadcastViewModel::setConnectable`. I know this was not written in this pull but still.

2025-01-08 01:18 UTC, mightytry commented on android/src/main/kotlin/com/github/picture2pc/android/viewmodel/mainscreenviewmodels/BroadcastViewModel.kt
> +    fun getName() = preferences.name.value
Why if name already exposed?

2025-01-08 01:18 UTC, mightytry commented on common/src/main/kotlin/com/github/picture2pc/common/data/preferences/PreferencesRepository.kt
> +data class Preferences(var name: String, var connectable: Boolean)
I think it is the best for this class to contain a function that checks if the values that it contains are valid. The `preferences` could be a State flow that replaces the `name` and `connectable` state flows. This way, it is easier to add new preferences. The `setConnectible` and `setName` functions could also be omitted and replaced by a single `setPreference`.

2025-01-08 01:18 UTC, mightytry commented on common/src/main/kotlin/com/github/picture2pc/common/data/preferences/PreferencesRepository.kt
> +    abstract fun loadPreferences(): Preferences
I overlooked it again... I think these aren't even needed. The `savePreferences` function is only called within the preferences' repository of the desktop part. And loading the Preferences can be done in the background at class creation. In the desktop part.

2025-01-08 01:18 UTC, mightytry commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/data/preferences/impl/DesktopPreferencesRepository.kt
Many changes here needed if other implementation.

2025-01-08 01:18 UTC, mightytry commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/data/preferences/impl/DesktopPreferencesRepository.kt
> +    }
File operations should be done within the ioDispatcher and backgroundScope

2025-01-08 01:18 UTC, mightytry commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/data/preferences/impl/DesktopPreferencesRepository.kt
> +    }
Also, no catching if file cannot be decoded bc corrupted → Should be just reset to default

2025-01-08 01:18 UTC, mightytry commented on common/src/main/kotlin/com/github/picture2pc/common/net/defaultdatatransmitter/impl/MulticastTcpDefaultDataTransmitter.kt
> +    open suspend fun sendPicture(payload: TcpPayload.Picture) {
Why? Not overwritten anywhere...

2025-01-08 01:18 UTC, mightytry commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/ui/main/MainWindow.kt
> +    preferencesRepository.loadPreferences()
Not needed if changed like discussed.

2025-01-08 01:18 UTC, mightytry commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/ui/main/elements/ConnectionInfo.kt
> +    val connectable = broadcastViewModel.getConnectable().collectAsState().value
Could be like: `val connectable = broadcastViewModel.preferences.collectAsState().value.name` if changed.

2025-01-08 01:18 UTC, mightytry commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/ui/main/elements/NameInputField.kt
Here also a few changes needed if other implementation.

2025-01-08 01:18 UTC, mightytry commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/viewmodel/mainscreen/BroadcastViewModel.kt
> +    fun nameIsInvalid(name: String) = preferences.nameIsInvalid(name)
This would also not be needed anymore because the safe Preferences function can throw/return an error why not accepted:

2025-01-08 01:18 UTC, mightytry commented on android/src/main/kotlin/com/github/picture2pc/android/viewmodel/mainscreenviewmodels/BroadcastViewModel.kt
> +            preferences.setConnectable(true)
Could be done in one step with new preferences.

2025-01-08 01:18 UTC, mightytry commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/viewmodel/mainscreen/BroadcastViewModel.kt
> +    fun nameIsInvalid(name: String) = preferences.nameIsInvalid(name)
```kotlin
sealed class Result(val color: Color, val displayName: String) {
    object OK :
        ClientState(StateColors.CONNECTED, "Online")

    sealed class ERROR(
        private val errorColor: Color,
        private val errorMessage: String
    ) :
        ClientState(errorColor, errorMessage) {

        object NAME_TO_LONG :
            ERROR(StateColors.NAME, "Could not save because the name was to long.")

        object NAME_INVALID_CHARS : ERROR(StateColors.NAME, "Name contained invalid chars.")
}
``

2025-03-04 16:31 UTC, GrumpyDucc commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/viewmodel/mainscreen/BroadcastViewModel.kt
> +    fun nameIsInvalid(name: String) = preferences.nameIsInvalid(name)
this is needed in some way since the save function is only triggered when the focus from the text field is lost, but an error needs to be detected on key stroke

2025-03-07 14:21 UTC, mightytry requested changes

2025-03-07 14:21 UTC, mightytry commented on android/src/main/kotlin/com/github/picture2pc/android/viewmodel/mainscreenviewmodels/BroadcastViewModel.kt
> +    fun getPreferences() = preferences.preferences
Why not with getter or immutable val?

2025-03-07 14:21 UTC, mightytry commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/viewmodel/mainscreen/BroadcastViewModel.kt
> +    fun nameIsInvalid(name: String) = preferences.nameIsInvalid(name)
Why? Is it not enough if you tell the user the name is not ok when the app tries to save it and tries to make it the new name networkwide?

2025-03-08 17:33 UTC, GrumpyDucc commented on android/src/main/kotlin/com/github/picture2pc/android/viewmodel/mainscreenviewmodels/BroadcastViewModel.kt
> +    fun getPreferences() = preferences.preferences
yes

2025-10-10 11:10 UTC, mightytry requested changes
Ig the functions setPreferences are not needed if you make the enteties (name, connectable) mutable stateflows instead. so one could simple set by writing to this an receive at another point by reading from it.

2025-10-10 11:10 UTC, mightytry commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/data/preferences/impl/DesktopPreferencesRepository.kt
> +    }
Ig file.exists is unnecessary
https://docs.oracle.com/javase/8/docs/api/java/io/File.html#createNewFile--
Atomically creates a new, empty file named by this abstract pathname if and only if a file with this name does not yet exist. The check for the existence of the file and the creation of the file if it does not exist are a single operation that is atomic with respect to all other filesystem activities that might affect the file.

2025-10-10 11:10 UTC, mightytry commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/viewmodel/mainscreen/BroadcastViewModel.kt
> +            preferences.setPreferences(newName, true)
why is connectable set to true if the name changed?

2025-10-10 11:10 UTC, mightytry commented on desktop/src/main/kotlin/com/github/picture2pc/desktop/viewmodel/mainscreen/BroadcastViewModel.kt
> +        scope.launch { preferences.setPreferences(connectable) }
why is the connectable boolean not saved after setting?

2025-10-10 11:10 UTC, mightytry commented on android/src/main/kotlin/com/github/picture2pc/android/data/serverpreferences/impl/AndroidPreferencesRepository.kt
>      override val connectable = context.settingsDataStore.data.map { preferences ->
compile errors

2025-10-13 10:44 UTC, mightytry approved these changes

2025-10-13 10:48 UTC, merged