Feature/android/66 image gallery picker
Picture2PC/Picture2Pc pull request #90
Opened 2024-12-24 16:47 UTC by GrumpyDucc

2025-01-01 17:23 UTC, GrumpyDucc commented
@mightytry picture injection needs to be updated to work with DetectedBox class

2025-01-07 17:01 UTC, GrumpyDucc commented
app crashes when the image is to large. unknown if file size or image resolution is the reason

2025-01-07 17:01 UTC, GrumpyDucc commented
fixed app crash when in horizontal mode

2025-01-07 17:05 UTC, GrumpyDucc commented
edge detection not working either

2025-01-08 10:46 UTC, mightytry commented
Are the crashes gone?

2025-01-11 11:54 UTC, GrumpyDucc commented
yes the crashes were fixed with the latest commit

2025-03-06 22:24 UTC, mightytry requested changes
Please test if crash when to many pictures. Also test edge detection.

2025-03-17 21:12 UTC, GrumpyDucc commented
does not crash since you can't select multiple images

2025-10-10 21:44 UTC, GrumpyDucc commented
the edge detection is still not working. other than that the feature is implemented

2025-10-13 08:15 UTC, mightytry commented
@GrumpyDucc Do you want to merge without edge detection working?
I would not..
And do you have any idea why it is not working?

2025-10-14 15:46 UTC, mightytry approved these changes

2025-10-14 15:50 UTC, mightytry commented
@GrumpyDucc can you please review my changes? (if they are ok)
Also it might be smart to offload some of the Image handling to common. Because we need to display both in mobile and desktop the points on the image. So in future it might be smart to put this part into common...

2025-10-14 20:33 UTC, merged